module.exports = {
  someSidebar: {
    Fundamentals: [
      '01-00-WhatIsReact',
      '01-01-WhyReact',
      '01-02-Comparison',
      '01-03-Architecture',
      '00-ComputerSetup',
      '00-VisualStudioCodeSetup',
      '02-Elements',
      '03-JSX',
      '04-VirtualDOM',
      '05-Components',
      'A6-ProjectSetup',
      {
        'Labs A': [
          {
            JavaScript: [
              'labs/js/00-Introduction',
              'labs/js/01-CreatingNewProject',
              'labs/js/02-RunningYourProject',
              'labs/js/03-StylesUsingCSS',
              'labs/js/04-YourFirstComponent',
              'labs/js/05-CreatingDataStructures',
            ],
            TypeScript: [
              'labs/ts/00-Introduction',
              'labs/ts/01-CreatingNewProject',
              'labs/ts/02-RunningYourProject',
              'labs/ts/03-StylesUsingCSS',
              'labs/ts/04-YourFirstComponent',
              'labs/ts/05-CreatingDataStructures',
            ],
          },
        ],
      },
      'A8-CodeOrganizationConventions',
      '06-Props',
      'A10-PropTypes',
      'A11-ReactTypeScript',
      '11-Lists',
      '07-Events',
      {
        'Labs B': [
          {
            JavaScript: [
              'labs/js/06-PassingDataToComponent',
              'labs/js/07-DisplayingListData',
              'labs/js/08-MoreReusableComponents',
              'labs/js/09-RespondingToEvent',
              'labs/js/10-CreatingForm',
            ],
            TypeScript: [
              'labs/ts/06-PassingDataToComponent',
              'labs/ts/07-DisplayingListData',
              'labs/ts/08-MoreReusableComponents',
              'labs/ts/09-RespondingToEvent',
              'labs/ts/10-CreatingForm',
            ],
          },
        ],
      },
      '08-Hooks',
      '08-State',
      '09-SideEffectsLifecyle',
      '10-ConditionalRendering',
      '12-ComponentArchitecture',
      'A22-Debugging',
      {
        'Labs C': [
          {
            JavaScript: [
              'labs/js/11-CommunicatingChildToParentComponent',
              'labs/js/12-HidingShowingComponents',
              'labs/js/13-MoreComponentCommunication',
              'labs/js/14-MultipleLevelComponentCommunication',
            ],
            TypeScript: [
              'labs/ts/11-CommunicatingChildToParentComponent',
              'labs/ts/12-HidingShowingComponents',
              'labs/ts/13-MoreComponentCommunication',
              'labs/ts/14-MultipleLevelComponentCommunication',
            ],
          },
        ],
      },
      '13-Forms',
      'A7-BackendAPISetup',
      '14-HTTP',
      {
        'Labs D': [
          {
            JavaScript: [
              'labs/js/15-FormValuesToState',
              'labs/js/16-FormValidation',
              'labs/js/17-SetupBackendRESTAPI',
              'labs/js/18-HTTP-GET',
              'labs/js/19-HTTP-PUT',
            ],
            TypeScript: [
              'labs/ts/15-FormValuesToState',
              'labs/ts/16-FormValidation',
              'labs/ts/17-SetupBackendRESTAPI',
              'labs/ts/18-HTTP-GET',
              'labs/ts/19-HTTP-PUT',
            ],
          },
        ],
      },
      '15-Routing',
      '17-BuildDeploy',
      {
        'Labs E': [
          {
            JavaScript: [
              'labs/js/20-RouterBasics',
              'labs/js/21-RouteParameters',
              'labs/js/22-BuildAndDeploy',
            ],
            TypeScript: [
              'labs/ts/20-RouterBasics',
              'labs/ts/21-RouteParameters',
              'labs/ts/22-BuildAndDeploy',
            ],
          },
        ],
      },
    ],
    Advanced: [
      '16-CustomHooks',
      'A17-OtherHooks',
      'A13-Context',
      'A25-StateManagement',
      '25-Testing',
      'A13-RenderProps',
      'A13-HigherOrderComponents',
      'A16-Security',
      'A23-Performance',
      'A9-Styling',
      // 'A14-Animations',
    ],
    Redux: [
      '21-Redux',
      '22-ReactRedux',
      '23-ReduxThunk',
      '24-ReactReduxThunk',
      'A12-ReduxTypeScript',
    ],
    Foundation: [
      'A1-PackageManager',
      'A2-CompilerSetup',
      'A3-ModernJavaScript',
      'A4-TypeScript',
      'A5-Promises',
      'A3-ECMAScriptReact',
    ],
    Resources: ['A24-UIComponents', 'A20-Resources'],
    Labs: [
      {
        JavaScript: [
          'labs/js/00-Introduction',
          'labs/js/01-CreatingNewProject',
          'labs/js/02-RunningYourProject',
          'labs/js/03-StylesUsingCSS',
          'labs/js/04-YourFirstComponent',
          'labs/js/05-CreatingDataStructures',
          'labs/js/06-PassingDataToComponent',
          'labs/js/07-DisplayingListData',
          'labs/js/08-MoreReusableComponents',
          'labs/js/09-RespondingToEvent',
          'labs/js/10-CreatingForm',
          'labs/js/11-CommunicatingChildToParentComponent',
          'labs/js/12-HidingShowingComponents',
          'labs/js/13-MoreComponentCommunication',
          'labs/js/14-MultipleLevelComponentCommunication',
          'labs/js/15-FormValuesToState',
          'labs/js/16-FormValidation',
          'labs/js/17-SetupBackendRESTAPI',
          'labs/js/18-HTTP-GET',
          'labs/js/19-HTTP-PUT',
          'labs/js/20-RouterBasics',
          'labs/js/21-RouteParameters',
          'labs/js/22-BuildAndDeploy',
          'labs/js/23-ReduxInstall',
          'labs/js/24-ReduxActionsReducer',
          'labs/js/25-ReduxWithReact',
          'labs/js/T1-FirstComponentTests',
          'labs/js/T2-SnapshotTests',
          'labs/js/T3-MoreTestingComponents',
          'labs/js/T4-NestedComponents',
          'labs/js/T5-ContainerComponents',
          'labs/js/T6-TestingForms',
          'labs/js/T7-ActionTests',
          'labs/js/T8-ReducerTests',
          'labs/js/T9-APITests',
          'labs/js/A1-SkippingLabs',
          {
            type: 'link',
            label: 'Snippets',
            href: 'https://github.com/craigmckeachie/snip',
          },
          {
            type: 'link',
            label: 'Solution Code',
            href: 'https://github.com/craigmckeachie/keeptrack-js',
          },
        ],
      },
      {
        TypeScript: [
          'labs/ts/00-Introduction',
          'labs/ts/01-CreatingNewProject',
          'labs/ts/02-RunningYourProject',
          'labs/ts/03-StylesUsingCSS',
          'labs/ts/04-YourFirstComponent',
          'labs/ts/05-CreatingDataStructures',
          'labs/ts/06-PassingDataToComponent',
          'labs/ts/07-DisplayingListData',
          'labs/ts/08-MoreReusableComponents',
          'labs/ts/09-RespondingToEvent',
          'labs/ts/10-CreatingForm',
          'labs/ts/11-CommunicatingChildToParentComponent',
          'labs/ts/12-HidingShowingComponents',
          'labs/ts/13-MoreComponentCommunication',
          'labs/ts/14-MultipleLevelComponentCommunication',
          'labs/ts/15-FormValuesToState',
          'labs/ts/16-FormValidation',
          'labs/ts/17-SetupBackendRESTAPI',
          'labs/ts/18-HTTP-GET',
          'labs/ts/19-HTTP-PUT',
          'labs/ts/20-RouterBasics',
          'labs/ts/21-RouteParameters',
          'labs/ts/22-BuildAndDeploy',
          'labs/ts/23-ReduxInstall',
          'labs/ts/24-ReduxActionsReducer',
          'labs/ts/25-ReduxWithReact',
          'labs/ts/T1-FirstComponentTests',
          'labs/ts/T2-SnapshotTests',
          'labs/ts/T3-MoreTestingComponents',
          'labs/ts/T4-NestedComponents',
          'labs/ts/T5-ContainerComponents',
          'labs/ts/T6-TestingForms',
          'labs/ts/T7-ActionTests',
          'labs/ts/T8-ReducerTests',
          'labs/ts/T9-APITests',
          'labs/ts/A1-SkippingLabs',
          {
            type: 'link',
            label: 'Snippets',
            href: 'https://github.com/craigmckeachie/snip',
          },
          {
            type: 'link',
            label: 'Solution Code',
            href: 'https://github.com/craigmckeachie/keeptrack-ts',
          },
        ],
      },
    ],
    Gatsby: [
      {
        Concepts: [
          'gatsby/concepts/00-Overview',
          'gatsby/concepts/01-Tooling',
          'gatsby/concepts/02-Components',
          'gatsby/concepts/03-Styling',
          'gatsby/concepts/04-Data',
          'gatsby/concepts/05-CSSGrid',
          'gatsby/concepts/06-Images',
          'gatsby/concepts/07-BuildDeployAudit',
          // 'gatsby/concepts/08-GraphQL',
        ],
        Labs: [
          'gatsby/labs/00-Overview',
          'gatsby/labs/01-Tooling',
          'gatsby/labs/02-Components',
          'gatsby/labs/03-Styling',
          'gatsby/labs/03a-Utility-First-Styling',
          'gatsby/labs/04-Data',
          'gatsby/labs/05-CSSGrid',
          'gatsby/labs/06-Images',
          'gatsby/labs/07-BuildDeployAudit',
          // 'gatsby/labs/08-GraphQL',
        ],
      },
    ],
  },
};
