module.exports = {
  someSidebar: {
    Fundamentals: [
      '01-Overview',
      '02-Elements',
      '03-JSX',
      '04-VirtualDOM',
      'A6-ProjectSetup',
      '05-Components',
      'A8-BestPractices',
      '06-Props',
      'A10-PropTypes',
      'A11-ReactTypeScript',
      '07-Events',
      '08-State',
      '09-SideEffectsLifecyle',
      '10-ConditionalRendering',
      '11-Lists',
      '12-ComponentArchitecture',
      '13-Forms',
      '14-HTTP',
      '15-Routing',
      '16-Hooks',
      '17-BuildDeploy',
    ],
    Advanced: [
      '25-Testing',
      'A1-PackageManager',
      'A2-CompilerSetup',
      'A3-ES6',
      'A3-ES6React',
      'A4-TypeScript',
      'A5-Promises',
      'A7-BackendAPISetup',
      'A9-Styling',

      'A13-AdvancedComponents',
      'A14-Animations',
      'A16-Security',
      'A20-Resources',
      'A21-FrameworksandLibraries',
      'A22-Debugging',
      'A23-Performance',
      'A24-UIComponents',
      'A25-StateManagement',
    ],
    Redux: [
      '21-Redux',
      '22-ReactRedux',
      '23-ReduxThunk',
      '24-ReactReduxThunk',
      'A12-ReduxTypeScript',
    ],
    Labs: ['doc1', 'doc2', 'doc3'],
  },
};
